"""make model score nullable

Revision ID: 019bf23a459e
Revises: 0b2b6b999f8d
Create Date: 2024-09-18 11:39:16.308423

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "019bf23a459e"
down_revision: Union[str, None] = "0b2b6b999f8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("image", "model_score", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("image", "model_score", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
