"""remove duplicate facility_id col

Revision ID: 02d9f04f4f98
Revises: 23b2c2b7400f
Create Date: 2024-09-23 07:29:21.519390

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "02d9f04f4f98"
down_revision: Union[str, None] = "23b2c2b7400f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
