"""make col name consistent

Revision ID: 0ef218f34b33
Revises: 11b0f16a508a
Create Date: 2025-01-09 11:19:22.720998

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ef218f34b33"
down_revision: Union[str, None] = "11b0f16a508a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_type_annotation",
        sa.Column("annotation_facility_hash", sa.String(), nullable=True),
    )
    op.drop_column("animal_type_annotation", "labeled_facility_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_type_annotation",
        sa.Column(
            "labeled_facility_uuid", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("animal_type_annotation", "annotation_facility_hash")
    # ### end Alembic commands ###
