"""add labeled facility uuid col to animal type annotation

Revision ID: 11b0f16a508a
Revises: 7b1f9568c926
Create Date: 2025-01-09 10:38:02.307003

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11b0f16a508a"
down_revision: Union[str, None] = "7b1f9568c926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_type_annotation",
        sa.Column("labeled_facility_uuid", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animal_type_annotation", "labeled_facility_uuid")
    # ### end Alembic commands ###
