"""make geometry multipoly actually

Revision ID: 192f3496fcd8
Revises: 95cb830a9723
Create Date: 2025-01-07 16:19:07.749500

"""

from typing import Sequence, Union

from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "192f3496fcd8"
down_revision: Union[str, None] = "95cb830a9723"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "census_block",
        "geometry",
        existing_type=Geography(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        type_=Geography(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "census_block",
        "geometry",
        existing_type=Geography(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        type_=Geography(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
