"""rename model score to bucket

Revision ID: 27bb77c3c7df
Revises: 019bf23a459e
Create Date: 2024-09-18 11:43:42.110005

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27bb77c3c7df"
down_revision: Union[str, None] = "019bf23a459e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("image", "model_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image",
        sa.Column("model_score", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
