"""fix hash uniqueness

Revision ID: 2cb7464cdb45
Revises: ed67141d86c2
Create Date: 2024-10-02 14:36:57.087072

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cb7464cdb45"
down_revision: Union[str, None] = "ed67141d86c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("facility_hash_key", "facility", type_="unique")
    op.create_index(
        "uq_facility_hash",
        "facility",
        ["hash"],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_facility_hash",
        table_name="facility",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_unique_constraint("facility_hash_key", "facility", ["hash"])
    # ### end Alembic commands ###
