"""add census block

Revision ID: 52f722e78213
Revises: 8676955b34f6
Create Date: 2025-01-07 16:02:21.889084

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "52f722e78213"
down_revision: Union[str, None] = "8676955b34f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "census_block",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statefp", sa.String(), nullable=False),
        sa.Column("countyfp", sa.String(), nullable=False),
        sa.Column("tractce", sa.String(), nullable=False),
        sa.Column("blockce", sa.String(), nullable=False),
        sa.Column("geoid", sa.String(), nullable=False),
        sa.Column("geoidfq", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mtfcc", sa.String(), nullable=False),
        sa.Column("ur", sa.String(), nullable=False),
        sa.Column("uace", sa.Integer(), nullable=False),
        sa.Column("funcstat", sa.String(), nullable=False),
        sa.Column("aland", sa.BigInteger(), nullable=False),
        sa.Column("awater", sa.BigInteger(), nullable=False),
        sa.Column("intptlat", sa.String(), nullable=False),
        sa.Column("intptlon", sa.String(), nullable=False),
        sa.Column("housing", sa.Integer(), nullable=False),
        sa.Column("pop", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            Geography(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_census_block_geometry",
        "census_block",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_census_block_geometry",
        table_name="census_block",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("census_block")
    # ### end Alembic commands ###
