"""add data field to annotation

Revision ID: 561356cf9e96
Revises: d2ae0ed484e2
Create Date: 2024-09-19 15:28:14.424772

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "561356cf9e96"
down_revision: Union[str, None] = "d2ae0ed484e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "construction_annotation", sa.Column("data", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("construction_annotation", "data")
    # ### end Alembic commands ###
