"""dd hash field to cafoannotation

Revision ID: 72a2552e913f
Revises: 76ebec8d7ca9
Create Date: 2024-12-17 16:18:36.099715

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72a2552e913f"
down_revision: Union[str, None] = "76ebec8d7ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafo_annotation",
        sa.Column("annotation_facility_hash", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cafo_annotation", "annotation_facility_hash")
    # ### end Alembic commands ###
