"""create irr annotation

Revision ID: 76ebec8d7ca9
Revises: d220983772a4
Create Date: 2024-12-09 09:45:08.071740

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "76ebec8d7ca9"
down_revision: Union[str, None] = "d220983772a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "irr_annotation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("annotated_at", sa.DateTime(), nullable=False),
        sa.Column("annotator", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["image.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("irr_annotation")
    # ### end Alembic commands ###
