"""add census block id to building

Revision ID: 7b1f9568c926
Revises: 192f3496fcd8
Create Date: 2025-01-07 17:20:24.361553

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b1f9568c926"
down_revision: Union[str, None] = "192f3496fcd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("building", sa.Column("census_block_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "building", "census_block", ["census_block_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "building", type_="foreignkey")
    op.drop_column("building", "census_block_id")
    # ### end Alembic commands ###
