"""add parcel number and constraint

Revision ID: 861144fdf6d4
Revises: 9206d9619013
Create Date: 2024-09-09 16:47:20.837322

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "861144fdf6d4"
down_revision: Union[str, None] = "9206d9619013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parcel", sa.Column("number", sa.String(), nullable=False))
    op.create_unique_constraint(None, "parcel", ["number", "county_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "parcel", type_="unique")
    op.drop_column("parcel", "number")
    # ### end Alembic commands ###
