"""make county multipolygon

Revision ID: 9206d9619013
Revises: 460e97ce76c5
Create Date: 2024-09-09 15:43:49.900434

"""

from typing import Sequence, Union

from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "9206d9619013"
down_revision: Union[str, None] = "460e97ce76c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "county",
        "geometry",
        existing_type=Geometry(
            geometry_type="POLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=Geometry(
            geometry_type="MULTIPOLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "county",
        "geometry",
        existing_type=Geometry(
            geometry_type="MULTIPOLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        type_=Geometry(
            geometry_type="POLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
