"""make uace nullable

Revision ID: 95cb830a9723
Revises: 3014b96c651b
Create Date: 2025-01-07 16:06:57.187048

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95cb830a9723"
down_revision: Union[str, None] = "3014b96c651b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("census_block", "uace", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("census_block", "uace", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
