"""give building annotation id

Revision ID: 9687e225fdc9
Revises: 903db37f6b99
Create Date: 2024-09-27 11:46:21.683132

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9687e225fdc9"
down_revision: Union[str, None] = "903db37f6b99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "building", sa.Column("image_annotation_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "building", "image_annotation", ["image_annotation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "building", type_="foreignkey")
    op.drop_column("building", "image_annotation_id")
    # ### end Alembic commands ###
