"""add unique to image annotaiton data

Revision ID: 9ff85ca9c925
Revises: c1939dbebc90
Create Date: 2024-10-04 10:47:25.139808

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ff85ca9c925"
down_revision: Union[str, None] = "c1939dbebc90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image_annotation", sa.Column("hash", sa.String(), nullable=False))
    op.drop_constraint(
        "image_annotation_annotated_at_image_id_key", "image_annotation", type_="unique"
    )
    op.create_unique_constraint(None, "image_annotation", ["hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "image_annotation", type_="unique")
    op.create_unique_constraint(
        "image_annotation_annotated_at_image_id_key",
        "image_annotation",
        ["annotated_at", "image_id"],
    )
    op.drop_column("image_annotation", "hash")
    # ### end Alembic commands ###
