"""add image_annotation

Revision ID: d2ae0ed484e2
Revises: 32813a3035af
Create Date: 2024-09-18 14:08:38.084365

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2ae0ed484e2"
down_revision: Union[str, None] = "32813a3035af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image_annotation", sa.Column("annotated_at", sa.DateTime(), nullable=False)
    )
    op.alter_column(
        "image_annotation", "image_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "image_annotation", "image_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("image_annotation", "annotated_at")
    # ### end Alembic commands ###
