"""remove image fkey, make parcel nullable

Revision ID: dd6d924a7d8d
Revises: 9687e225fdc9
Create Date: 2024-09-27 11:48:27.545107

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd6d924a7d8d"
down_revision: Union[str, None] = "9687e225fdc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("building", "parcel_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("building_image_id_fkey", "building", type_="foreignkey")
    op.drop_column("building", "image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "building",
        sa.Column("image_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "building_image_id_fkey", "building", "image", ["image_id"], ["id"]
    )
    op.alter_column("building", "parcel_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
