"""switch to general geometry type

Revision ID: eb0e00cdb897
Revises: 6a14adc49f24
Create Date: 2024-10-14 10:48:00.587956

"""

from typing import Sequence, Union

from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "eb0e00cdb897"
down_revision: Union[str, None] = "6a14adc49f24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "urban_mask",
        "geometry",
        existing_type=Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=Geometry(
            srid=4326, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "urban_mask",
        "geometry",
        existing_type=Geometry(
            srid=4326, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
        ),
        type_=Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
