"""make county id nullable

Revision ID: ed67141d86c2
Revises: df12e8368dc7
Create Date: 2024-10-01 17:55:24.383090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed67141d86c2"
down_revision: Union[str, None] = "df12e8368dc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("facility", "county_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("facility", "county_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
