"""add extra fields to animal typing

Revision ID: f90e1621815b
Revises: 02d9f04f4f98
Create Date: 2024-09-23 07:35:53.814478

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f90e1621815b"
down_revision: Union[str, None] = "02d9f04f4f98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_type_annotation", sa.Column("annotated_by", sa.String(), nullable=False)
    )
    op.add_column(
        "animal_type_annotation", sa.Column("notes", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animal_type_annotation", "notes")
    op.drop_column("animal_type_annotation", "annotated_by")
    # ### end Alembic commands ###
