"""add annotated_by field to cafo annotation

Revision ID: fd3fcae5965a
Revises: f90e1621815b
Create Date: 2024-09-23 07:40:30.673799

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd3fcae5965a"
down_revision: Union[str, None] = "f90e1621815b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafo_annotation", sa.Column("annotated_by", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cafo_annotation", "annotated_by")
    # ### end Alembic commands ###
